#Set sample names
SAMPLES: ["V_D2_Rep_1", "V_D2_Rep_2", "V_D2_Rep_3", "V_D7_Rep_1", "V_D7_Rep_2", "V_D7_Rep_3", "V_D14_Rep_1", "V_D14_Rep_2", "V_D14_Rep_3", "C_D2_Rep_1", "C_D2_Rep_2", "C_D2_Rep_3", "C_D7_Rep_1", "C_D7_Rep_2", "C_D7_Rep_3", "C_D14_Rep_1", "C_D14_Rep_2", "C_D14_Rep_3]

#Set group ID
GROUP_ID: ["1", "1", "1", "1", "1", "1", "1", "1", "1", "2", "2", "2", "2", "2", "2", "2", "2", "2"]
GROUP_MAX: "2"

#Set reference genome and transcriptome annotation file
GENOME: "genomes/anSteph-astel2.fa"
GENOME_LINK: "https://www.vectorbase.org/download/anopheles-stephensi-indianscaffoldsastei2fagz"
#Note - Genome annotation must be in GTF format
GENOME_ANNOTATION: "genomes/anStph-astel2.gtf"
GENOME_ANNOTATION_LINK: "https://www.vectorbase.org/download/anopheles-stephensi-indianbasefeaturesastei23gtfgz"

#Define important paths
ADAPTERS: "/storage/work/cxb585/bin/Trimmomatic-0.36/adapters/TruSeq3-PE.fa"

#Tools necessary to run
TOOLS: ["bamtools", "bcftools", "tophat", "gatk", "picard", "python", "samtools", "trimmomatic", "vcftools"]
