#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N fastqc
#PBS -m abe

# -------------------------------------------------- #
#run fastqc
# -------------------------------------------------- #

#load modules
module load fastqc 

#move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/data/processedData/aligned_reads/quality_filter/

#generate star index
for file in *bam; do fastqc $file; done

exit;
