#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N formatRef
#PBS -m abe

# -------------------------------------------------- #
#format reference genome
# -------------------------------------------------- #

#load modules
module load bwa samtools picard fastx bowtie star 

#move to correct directory
cd ~/scratch/RNAseq/genomes/

#index reference
bwa index -a bwtsw StephScaffold.fa

#generate index file
samtools faidx StephScaffold.fa

#generate sequencing directory
java -jar /storage/work/cxb585/bin/picard-2.10.10/picard.jar CreateSequenceDictionary REFERENCE=StephScaffold.fa OUTPUT=StephScaffold.dict  

#generate star index
STAR --runMode genomeGenerate --genomeDir . --genomeFastaFiles StephScaffold.fa --sjdbGTFfile StephScaffold.gtf --sjdbOverhang 74

exit;
