#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N formatRef
#PBS -m abe

# -------------------------------------------------- #
#format reference genome
# -------------------------------------------------- #

#load modules
module load bwa samtools picard fastx bowtie star 

#move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/genomes/

#index reference
bwa index -a bwtsw anophelesStephensiScaffold-asteL2.3.fa

#generate index file
samtools faidx anophelesStephensiScaffold-asteL2.3.fa

#generate sequencing directory
java -jar /storage/work/cxb585/bin/picard-2.10.10/picard.jar CreateSequenceDictionary REFERENCE=anophelesStephensiScaffold-asteL2.3.fa OUTPUT=anophelesStephensiScaffold-asteL2.3.dict  

#generate bowtie index
bowtie2-build anophelesStephensiScaffold-asteL2.3.fa anophelesStephensiScaffold-asteL2.3

#generate star index
STAR --runMode genomeGenerate --genomeDir . --genomeFastaFiles anophelesStephensiScaffold-asteL2.3.fa --sjdbGTFfile anophelesStephensiBaseFeatures-asteL2.3.gtf --sjdbOverhang 74

exit;
