#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l pmem=32gb
#PBS -l walltime=36:00:00
#PBS -M coalhende@gmail.com
#PBS -N diffExpPipeTest
#PBS -m abe

#------------------------------------------------
# Test RNAseq pipeline
#-----------------------------------------------

# move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/guidedExample/

# run test pipeline
conda activate bioinfo
./runGuidedExample.sh

exit;
