#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=8gb
#PBS -l walltime=36:00:00
#PBS -M coalhende@gmail.com
#PBS -N snakemake_run
#PBS -m abe

# -------------------------------------------------- #
#Run snakemake!
# -------------------------------------------------- #

#move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/

#run snakemake
conda activate bioinfo
snakemake --unlock
snakemake --ri -j 2 --cluster "qsub -A open -l walltime=24:00:00,nodes=1:ppn=8,pmem=32gb"

exit;
