#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l pmem=8gb
#PBS -l walltime=36:00:00
#PBS -N snakemake_run
#PBS -m abe

# -------------------------------------------------- #
#Run snakemake!
# -------------------------------------------------- #

#move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/

#run snakemake
conda activate bioinfo
snakemake --unlock
snakemake --ri -j 182 --cluster-config cluster.yaml --cluster "qsub -A {cluster.QUEUE} -l walltime={cluster.WALLTIME} -l nodes={cluster.NODES}:ppn={cluster.PPN} -l pmem={cluster.PMEM} -M {cluster.EMAIL} -m abe"

exit;
