#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=24:00:00
#PBS -M coalhende@gmail.com
#PBS -N starIndex
#PBS -m abe

# -------------------------------------------------- #
#format reference genome
# -------------------------------------------------- #

#load modules
module load star 

#move to correct directory
cd ~/scratch/stephensiTranscriptome-november2018-mayvInf/genomes/

#generate star index
STAR --runMode genomeGenerate --genomeDir . --genomeFastaFiles anophelesStephensiScaffold-asteL2.3.fa --sjdbGTFfile anophelesStephensiBaseFeatures-asteL2.3.gtf --sjdbOverhang 74

exit;
